# Generated by Django 4.2.23 on 2025-07-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Name of the region', max_length=255)),
                ('area_type', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban'), ('Mixed', 'Mixed')], help_text='Type of area: Rural, Urban, or Mixed', max_length=10)),
                ('levels_config', models.JSONField(help_text="For Rural/Urban, an integer for levels; for Mixed, a dict with 'urban' and 'rural' keys")),
                ('payments', models.JSONField(help_text='Array of payment amounts matching the levels')),
                ('is_paying', models.BooleanField(default=True, help_text='Whether this is a paying membership type (False for indigent)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Type',
                'verbose_name_plural': 'Membership Types',
                'unique_together': {('region', 'area_type', 'is_paying')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Name of the member or family', max_length=255)),
                ('member_id', models.CharField(help_text='Unique identifier for the member', max_length=50, unique=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='Membership level (1-based index)')),
                ('start_date', models.DateField(help_text='When the membership starts')),
                ('end_date', models.DateField(help_text='When the membership ends')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', help_text='Current status of the membership', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_type', models.ForeignKey(help_text='The type of this membership', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='membership.membershiptype')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
